# Generated by Django 4.1.5 on 2023-01-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permalink",
            name="encode",
        ),
    ]
